
name: "Container Pipeline"

on:
  push:
    branches:
    - main

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Container Pipeline'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1
    
    # Install Python
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.5'
    
    # Install Dependencies
    - name: Install Dependencies
      run: |
         pip3 install -r VulnerableWebApp/requirements.txt     
        
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: |
          --command=python3 
          VulnerableWebApp/

    # Build Docker Image
    - name: Build Container Image
      run: |
         sudo docker build . -t michaelbraunbass/snyk-demo    
    
    # Scan Container w/ Snyk
    - name: Scan container w/ Snyk
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: michaelbraunbass/snyk-demo 
        args: --file=Dockerfile

 # This feature requires github enterprise  
 #   - name: Upload scan results to Github
 #     uses: github/codeql-action/upload-sarif@v1
 #     with:
 #       sarif_file: snyk.sarif
